language: php
php:
- 5.4
- 5.5
env:
  global:
  - OA=oauth1
  # termi
  - secure: eR5eq5E58d+hsFPS5jdqqRidmJ8squKtW5DYZ9ERtLCPFUbu9+Ub+BS0SSmPTS7P9V4W1kH8lIu1OrImay1yR/eAUFfBjN298309TbAIBV5isRxr9ppsCcNGkDTCGVHNq3/3Lo8oP8aFEgHgnwHgsEVyxFDXKa+TIe7AuOW69hc=
  - secure: QflW2td+TJ6tsJbb8+k4DOLXMOsurvZZidCIgyC2y1HkQ6ho8L6OYkYcVk8lLCMvL0sVh9E3CUaWOElKYVN+cHd0NBkHo/WaEwHjPqtor+G/vx4QhLxOaKu7EnrsBgesMmdiD8OQdf5y5+eJvgb3cUsEWxzPAA0uJrCEVHtHCso=
script: phpunit --colors --configuration phpunit.$OA.xml --coverage-text --coverage-clover=coverage.clover
after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
  email: sudocoder@ymail.com
